In [31]:
import os 
import glob 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [32]:
path = './data/data_noNull.csv'

In [33]:
data = pd.read_csv(path)

data.head()

,date,sample_time_continuous_caster,steel_type,doc_requirement,"workpiece_weight, tonn",workpiece_slice_geometry_150x150,cast_in_row,alloy_type_open,"alloy_speed, meter/minute","steel_weight_theoretical, tonn",...,"Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,"quantity, tonn",num_crystallizer,num_stream,RUL
0,2020-01-05,2020-01-05 00:20:12,St3sp,Contract,163.8,1,18,1,3,164.2,...,0.0007,0.0037,0.0,0.0,0.0,30013346,0.01,2,1,814.0
1,2020-01-05,2020-01-05 00:20:12,St3sp,Contract,163.8,1,18,1,3,164.2,...,0.0007,0.0037,0.0,0.0,0.0,30013350,0.01,5,2,0.0
2,2020-01-05,2020-01-05 00:20:12,St3sp,Contract,163.8,1,18,1,3,164.2,...,0.0007,0.0037,0.0,0.0,0.0,30012261,0.01,22,4,0.0
3,2020-01-05,2020-01-05 14:59:52,St3sp,Contract,161.7,1,6,1,3,162.1,...,0.0011,0.0056,0.0,0.0,0.0,30013346,0.03,2,1,1148.0
4,2020-01-05,2020-01-05 14:59:52,St3sp,Contract,161.7,1,6,1,3,162.1,...,0.0011,0.0056,0.0,0.0,0.0,30013350,0.03,5,2,341.0

In [34]:
data['steel_type'].value_counts()

steel_type
Arm500    7916
St4sp      833
St3sp      425
25G2S      304
1015       184
1018        95
Name: count, dtype: int64

In [35]:
data['steel_type'] = data['steel_type'].astype('category')
data['steel_type'] = data['steel_type'].cat.codes

In [36]:
data.head()

,date,sample_time_continuous_caster,steel_type,doc_requirement,"workpiece_weight, tonn",workpiece_slice_geometry_150x150,cast_in_row,alloy_type_open,"alloy_speed, meter/minute","steel_weight_theoretical, tonn",...,"Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,"quantity, tonn",num_crystallizer,num_stream,RUL
0,2020-01-05,2020-01-05 00:20:12,4,Contract,163.8,1,18,1,3,164.2,...,0.0007,0.0037,0.0,0.0,0.0,30013346,0.01,2,1,814.0
1,2020-01-05,2020-01-05 00:20:12,4,Contract,163.8,1,18,1,3,164.2,...,0.0007,0.0037,0.0,0.0,0.0,30013350,0.01,5,2,0.0
2,2020-01-05,2020-01-05 00:20:12,4,Contract,163.8,1,18,1,3,164.2,...,0.0007,0.0037,0.0,0.0,0.0,30012261,0.01,22,4,0.0
3,2020-01-05,2020-01-05 14:59:52,4,Contract,161.7,1,6,1,3,162.1,...,0.0011,0.0056,0.0,0.0,0.0,30013346,0.03,2,1,1148.0
4,2020-01-05,2020-01-05 14:59:52,4,Contract,161.7,1,6,1,3,162.1,...,0.0011,0.0056,0.0,0.0,0.0,30013350,0.03,5,2,341.0

In [37]:
data['steel_type'].value_counts()

steel_type
3    7916
5     833
4     425
2     304
0     184
1      95
Name: count, dtype: int64

In [38]:
data['doc_requirement'].value_counts()

doc_requirement
DOC 34028-2016        7916
Contract              1258
DOC 5781-82            304
ASTM A510/A510M-18     279
Name: count, dtype: int64

In [39]:
data['doc_requirement'] = data['doc_requirement'].astype('category')
data['doc_requirement'] = data['doc_requirement'].cat.codes

In [40]:
data['doc_requirement'].value_counts()

doc_requirement
2    7916
1    1258
3     304
0     279
Name: count, dtype: int64

In [41]:
data = data.drop(labels=['date', 'sample_time_continuous_caster'],axis=1)

data.head()

,steel_type,doc_requirement,"workpiece_weight, tonn",workpiece_slice_geometry_150x150,cast_in_row,alloy_type_open,"alloy_speed, meter/minute","steel_weight_theoretical, tonn","steel_weight, tonn",grab1_num,...,"Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,"quantity, tonn",num_crystallizer,num_stream,RUL
0,4,1,163.8,1,18,1,3,164.2,163.8,5.0,...,0.0007,0.0037,0.0,0.0,0.0,30013346,0.01,2,1,814.0
1,4,1,163.8,1,18,1,3,164.2,163.8,5.0,...,0.0007,0.0037,0.0,0.0,0.0,30013350,0.01,5,2,0.0
2,4,1,163.8,1,18,1,3,164.2,163.8,5.0,...,0.0007,0.0037,0.0,0.0,0.0,30012261,0.01,22,4,0.0
3,4,1,161.7,1,6,1,3,162.1,161.7,3.0,...,0.0011,0.0056,0.0,0.0,0.0,30013346,0.03,2,1,1148.0
4,4,1,161.7,1,6,1,3,162.1,161.7,3.0,...,0.0011,0.0056,0.0,0.0,0.0,30013350,0.03,5,2,341.0

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9757 entries, 0 to 9756
Data columns (total 46 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   steel_type                                                   9757 non-null   int8
 1   doc_requirement                                              9757 non-null   int8
 2   workpiece_weight, tonn                                       9757 non-null   float64
 3   workpiece_slice_geometry_150x150                             9757 non-null   int64
 4   cast_in_row                                                  9757 non-null   int64
 5   alloy_type_open                                              9757 non-null   int64
 6   alloy_speed, meter/minute                                    9757 non-null   int64
 7   steel_weight_theoretical, tonn                               9757 non-null   float64
 8   steel_weight, tonn                                           9757 non-null   float64
 9   grab1_num                                                    9757 non-null   float64
 10  steel_temperature_grab1, Celsius deg.                        9757 non-null   float64
 11  metal_residue_grab1, tonn                                    9757 non-null   float64
 12  grab2_num                                                    9757 non-null   float64
 13  resistance, tonn                                             9757 non-null   float64
 14  swing_frequency, amount/minute                               9757 non-null   int64
 15  crystallizer_movement, mm                                    9757 non-null   int64
 16  water_consumption, liter/minute                              9757 non-null   int64
 17  water_temperature_delta, Celsius deg.                        9757 non-null   int64
 18  water_consumption_secondary_cooling_zone_num1, liter/minute  9757 non-null   int64
 19  water_consumption_secondary_cooling_zone_num2, liter/minute  9757 non-null   int64
 20  water_consumption_secondary_cooling_zone_num3, liter/minute  9757 non-null   float64
 21  Ce, %                                                        9757 non-null   float64
 22  C, %                                                         9757 non-null   float64
 23  Si, %                                                        9757 non-null   float64
 24  Mn,%                                                         9757 non-null   float64
 25  S, %                                                         9757 non-null   float64
 26  P, %                                                         9757 non-null   float64
 27  Cr, %                                                        9757 non-null   float64
 28  Ni, %                                                        9757 non-null   float64
 29  Cu, %                                                        9757 non-null   float64
 30  As, %                                                        9757 non-null   float64
 31  Mo, %                                                        9757 non-null   float64
 32  Nb, %                                                        9757 non-null   float64
 33  Ti, %                                                        9757 non-null   float64
 34  V, %                                                         9757 non-null   float64
 35  Al, %                                                        9757 non-null   float64
 36  Ca, %                                                        9757 non-null   float64
 37  N, %                                                         9757 non-null   float64
 38  Pb, %                                                        9757 non-null   float64
 39  Mg, %                                                        9757 non-null   float64
 40  Zn, %                                                        9757 non-null   float64
 41  sleeve                                                       9757 non-null   int64
 42  quantity, tonn                                               9757 non-null   float64
 43  num_crystallizer                                             9757 non-null   int64
 44  num_stream                                                   9757 non-null   int64
 45  RUL                                                          9757 non-null   float64
dtypes: float64(31), int64(13), int8(2)
memory usage: 3.3 MB

### 1. RUL을 제거하고 Steel_stype 예측하기 

### 2. RUL포함하고 Steel_stype 예측하기

In [43]:
data = data.drop(labels=['RUL'],axis=1)

data.head()

,steel_type,doc_requirement,"workpiece_weight, tonn",workpiece_slice_geometry_150x150,cast_in_row,alloy_type_open,"alloy_speed, meter/minute","steel_weight_theoretical, tonn","steel_weight, tonn",grab1_num,...,"Al, %","Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,"quantity, tonn",num_crystallizer,num_stream
0,4,1,163.8,1,18,1,3,164.2,163.8,5.0,...,0.0039,0.0007,0.0037,0.0,0.0,0.0,30013346,0.01,2,1
1,4,1,163.8,1,18,1,3,164.2,163.8,5.0,...,0.0039,0.0007,0.0037,0.0,0.0,0.0,30013350,0.01,5,2
2,4,1,163.8,1,18,1,3,164.2,163.8,5.0,...,0.0039,0.0007,0.0037,0.0,0.0,0.0,30012261,0.01,22,4
3,4,1,161.7,1,6,1,3,162.1,161.7,3.0,...,0.0033,0.0011,0.0056,0.0,0.0,0.0,30013346,0.03,2,1
4,4,1,161.7,1,6,1,3,162.1,161.7,3.0,...,0.0033,0.0011,0.0056,0.0,0.0,0.0,30013350,0.03,5,2

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler, MinMaxScaler, StandardScaler

In [45]:
X = data.drop(['steel_type'], axis=1)
y = data['steel_type']

In [46]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=2023, shuffle=True)
X_val, X_test, y_val, y_test = train_test_split(X_val, y_val, test_size=0.2, random_state=2023, shuffle=True)

In [47]:
class Pipeline:
    def __init__(self, scalar):
        self.scalar = scalar
    
    def fit(self, X, y):
        X = self.scalar.fit_transform(X)
        return X, y
    
    def transform(self, X, y):
        X = self.scalar.transform(X)
        return X, y

In [48]:
scaler = RobustScaler()     # RobustScaler, MinMaxScaler, StandardScaler
pipeline = Pipeline(scaler)

In [49]:
X_train_s, y_train_s = pipeline.fit(X_train, y_train)
X_val_s, y_val_s = pipeline.transform(X_val, y_val)

X_test_s, y_test_s = pipeline.transform(X_test, y_test)

In [50]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report

models = {
    "KNeighborsClassifier": {"model":KNeighborsClassifier(n_neighbors=5)},
    "DecisionTreeClassifier": {"model":DecisionTreeClassifier()},
    "LogisticRegression": {"model":LogisticRegression()},
    "RandomForestClassifier": {"model":RandomForestClassifier()},
    "XGBClassifier": {"model":XGBClassifier()},
    "LGBMClassifier": {"model":LGBMClassifier(verbose=-1)}
}

In [ ]:
from time import perf_counter

# Train모델 학습
for name, model in models.items():
    model = model['model']
    start = perf_counter()
    
    history = model.fit(X_train_s, y_train_s)
    
    # 학습시간과 val_accuracy 저장
    duration = perf_counter() - start
    duration = round(duration,2)
    models[name]['perf'] = duration
    
    y_train_pred = model.predict(X_train_s)
    y_val_pred = model.predict(X_val_s)
    
    train_score = round(model.score(X_train_s, y_train_s),4)
    val_score = round(model.score(X_val_s, y_val_s),4)
    
    models[name]['train_score'] = train_score
    models[name]['val_score'] = val_score
    
    print(f"{name:20} trained in {duration} sec, train_score: {train_score}. val_score: {val_score}")
    
# Create a DataFrame with the results
models_result = []

for name, v in models.items():
    models_result.append([ name, models[name]['val_score'], 
                          models[name]['perf']])
    
df_results = pd.DataFrame(models_result, 
                          columns = ['model','val_score','Training time (sec)'])
df_results.sort_values(by='val_score', ascending=False, inplace=True)
df_results.reset_index(inplace=True,drop=True)
df_results

In [ ]:
def check_performance_for_model(df_results):
    plt.figure(figsize = (15,5))
    sns.barplot(x = 'model', y = 'val_score', data = df_results)
    plt.title('ACC (%) on the Test set', fontsize = 15)
    plt.ylim(0,1.2)
    plt.xticks(rotation=90)
    plt.show()
    
check_performance_for_model(df_results)

In [ ]:


model = XGBClassifier()

model.fit(X_train_s, y_train_s)

y_test_pred = model.predict(X_test_s)
test_score = round(model.score(X_test_s, y_test_s),4)

print('acc:', test_score)
print(classification_report(y_test, y_test_pred))

In [ ]:
def eval_graph(y_valid, y_pred, cnt):
    plt.figure(figsize=(18,6))
    plt.plot(y_valid.values[:cnt], label='Actual',  marker = 'o', markersize=5)
    plt.plot(y_pred[:cnt], label='Predicted', alpha = 0.6,  marker = 'o', markersize=10)
    plt.legend()
    plt.ylabel('RUL')
    plt.show()

eval_graph(y_test_s, y_test_pred, 250)

In [ ]:
# 데이터프레임 만들기
perf_dic = {'feature':list(X),
            'importance': model.feature_importances_}
df = pd.DataFrame(perf_dic)
df.sort_values(by='importance', ascending=True, inplace=True)

# 시각화
plt.figure(figsize=(5, 10))
plt.barh(df['feature'], df['importance'])
plt.show()